
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sal Learns to Code
email: salonicmd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there!! Welcome to my page!
  I'm using this website to create a portolio and to blog about the skills I am learning.
  Please get in touch!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: saloni1990
github_username:  saloni1990
linkedin_username:  saloni1990
# Build settings
markdown: kramdown
